project:
  type: docusaurus
  output-dir: "."
  render:
    - "src/content/**/*.qmd"
  post-render:
    - "uv run python fix-callouts.py src/content/docs/examples/quarto.md"

format:
  commonmark:
    embed-resources: true
    template: starlight-template.md

execute:
  echo: false
  warning: false
  ojs: true

metadata:
  title-block-banner: false