[project]
name = "bedrock-web"
version = "0.1.0"
description = "Bedrock's website & docs site"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bedrock-ge>=0.3.2",
    "pydoc-markdown>=4.8.2",
]
