[project]
name = "bedrock-astro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "bedrock-ge>=0.2.4",
    "pydoc-markdown>=4.8.2",
]
